### ISSUE TITLE
Rendre dynamique les paramètres de la commande qm

### ISSUE THREAD

**Issue by darkweak** [ZrH-Source/install-vm#3]
Afin de pouvoir configurer dynamiquement la commande qm exécutée pour démarrer une VM, il faudra alors faire en sorte que les paramètres soient récupérés depuis un fichier de configuration yaml.  
`ansible-playbook -i hosts main.yml -e @extra-vars.yml`

Il faudra donc définir les clés suivantes dans le fichier extra-vars.yml
- id
- name
- memory
- socket
- iso

```yaml
id: 100
name: debian
memory: 2048
socket: 2
iso: debian-11.3.0-amd64-netinst.iso
```

Et dans le playbook main, récupérer ces valeurs et les passer à la place des arguments en dur.

`'qm create {{ id }} ...'`
